# 5.9 Recuperação 
- [5.9 Recuperação](#59-recuperação)
  - [O que é?](#o-que-é)
  - [Quando usar?](#quando-usar)
  - [Como usar?](#como-usar)

## O que é?

Go possibilita a recuperação de um pânico, usando a função interna de recuperação/`recover`. Uma recuperação pode impedir um pânico de abortar o programa e deixá-lo continuar com a execução.


Um exemplo de onde isso pode ser útil: um servidor não gostaria de travar se uma das conexões do cliente apresentar um erro crítico. Em vez disso, o servidor deseja fechar a conexão e continuar atendendo a outros clientes. E isso é feito por padrão pelo pacote net/http do Go para servidores HTTP.

## Quando usar?
Quando quiser recuperar de um pânico.

`recover` deve ser chamada dentro de uma função adiada`defer`. Quando a função em questão entrar em pânico, o adiamento será ativado e uma chamada de `recover` dentro dele capturará o pânico.
O valor de retorno de recover é o erro gerado na chamada para panic.
```
package main

import "fmt"

func mayPanic() {
    panic("a problem")
}

func main() {

    defer func() {
        if r := recover(); r != nil {

            fmt.Println("Recovered. Error:\n", r)
        }
    }()

    mayPanic()

    fmt.Println("After mayPanic()")
}
 ```

 Este código não será executado, porque mayPanic entra em pânico. A execução da main para no ponto de pânico e recomeça no defer.


## Como usar?
veja aqui: https://go.dev/play/p/sGmC74_qt6Q